# Generated by Django 3.1.8 on 2021-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
