# Generated by Django 3.1.6 on 2021-03-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210301_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'MailList Request',
                'verbose_name_plural': 'MailList Requests',
            },
        ),
    ]
