# Generated by Django 3.1.6 on 2021-03-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedbackcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackcontact',
            name='name',
        ),
        migrations.AddField(
            model_name='feedbackcontact',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
