# Generated by Django 3.1.6 on 2021-04-04 18:25

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_policeupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeupload',
            name='file',
        ),
        migrations.AddField(
            model_name='policeupload',
            name='form',
            field=models.FileField(default='post', upload_to=app.models.upload_path),
        ),
        migrations.CreateModel(
            name='MemberUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.FileField(upload_to=app.models.upload_path)),
                ('frontDL', models.FileField(upload_to=app.models.upload_path)),
                ('backDL', models.FileField(upload_to=app.models.upload_path)),
                ('carReg', models.FileField(upload_to=app.models.upload_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
