# Generated by Django 3.1.6 on 2021-04-04 18:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210404_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeupload',
            name='form',
            field=models.FileField(upload_to=app.models.upload_path),
        ),
    ]
