# Generated by Django 3.1.6 on 2021-04-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210404_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberupload',
            options={'verbose_name': 'Member Upload', 'verbose_name_plural': 'Member Uploads'},
        ),
        migrations.AlterModelOptions(
            name='policeupload',
            options={'verbose_name': 'Police Upload', 'verbose_name_plural': 'Police Uploads'},
        ),
    ]
