# Generated by Django 3.1.6 on 2021-04-04 19:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210404_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberupload',
            name='backDL',
            field=models.ImageField(upload_to=app.models.upload_path),
        ),
        migrations.AlterField(
            model_name='memberupload',
            name='carReg',
            field=models.ImageField(upload_to=app.models.upload_path),
        ),
        migrations.AlterField(
            model_name='memberupload',
            name='frontDL',
            field=models.ImageField(upload_to=app.models.upload_path),
        ),
    ]
